### PR TITLE
Only add default Content Type if not set

### PR DESCRIPTION
**Pull request by rsertelon**
> Linked to #14

I'm sorry I didn't see it earlier. Only adds default Content-Type header if not set by user.

### CODE REVIEW

**Comment by rsertelon** [comment]
@nmorel when do you think you could release a bug fix with this one please?

Thanks ;)

**Comment by nmorel** [comment]
I may find some time this week, maybe tomorrow.
Without the jenkins, I only managed to deploy a release from an old ubuntu install at home (only OS with the correct version of gpg).

**Comment by rsertelon** [comment]
Thanks a lot, sorry for pushing it like this, I'm the one who made the mistake ;)

**Comment by nmorel** [comment]
v0.5.1 available

**Comment by rsertelon** [comment]
Thanks a lot! :)

**Pull request merged**
